"""Shared utilities for trading and analysis modules."""

from .constants import (
    GAP_THRESHOLD,
    MIN_PRICE,
    MIN_VOLUME,
    VOLUME_MULTIPLIER,
)
from .container import DIContainer, create_container
from .exceptions import (
    CandidateRepositoryError,
    ConfigurationError,
    DatabaseError,
    DiscordNotificationError,
    GapCalculationError,
    IBKRAuthenticationError,
    IBKRClientError,
    IBKRConnectionError,
    IBKRRequestError,
    NotificationError,
    OrderError,
    PositionError,
    PositionRepositoryError,
    RepositoryError,
    ScannerError,
    ScannerValidationError,
    SkimError,
    TradingError,
)

__all__ = [
    "MIN_PRICE",
    "MIN_VOLUME",
    "GAP_THRESHOLD",
    "VOLUME_MULTIPLIER",
    "DIContainer",
    "create_container",
    "SkimError",
    "IBKRClientError",
    "IBKRAuthenticationError",
    "IBKRConnectionError",
    "IBKRRequestError",
    "ScannerError",
    "ScannerValidationError",
    "GapCalculationError",
    "TradingError",
    "OrderError",
    "PositionError",
    "DatabaseError",
    "RepositoryError",
    "CandidateRepositoryError",
    "PositionRepositoryError",
    "ConfigurationError",
    "NotificationError",
    "DiscordNotificationError",
]
